/**
 * triage/pdf.ts
 *
 * Clinical-style PDF report exporter for a triage session.
 *
 * Built with jsPDF for browser-native generation — no server round-trip.
 * The output is intentionally formatted like a one-page clinical handout the
 * user can email or print and bring to their PT / physician.
 */

import { jsPDF } from 'jspdf'
import type { TriageChatMessage, DifferentialPayload } from './llm'
import type { MuscleContribution } from '../diagnostic'

interface ExportOpts {
  patientName?:  string
  sessionDate:   Date
  history:       TriageChatMessage[]
  differential:  DifferentialPayload
  contributions: MuscleContribution[]
}

const MARGIN = 50

export function exportTriagePdf(opts: ExportOpts): void {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' })
  const pageW = doc.internal.pageSize.getWidth()
  const pageH = doc.internal.pageSize.getHeight()
  let y = MARGIN

  const writeLine = (text: string, size = 10, bold = false) => {
    doc.setFont('helvetica', bold ? 'bold' : 'normal')
    doc.setFontSize(size)
    const lines = doc.splitTextToSize(text, pageW - MARGIN * 2) as string[]
    for (const line of lines) {
      if (y > pageH - MARGIN) { doc.addPage(); y = MARGIN }
      doc.text(line, MARGIN, y)
      y += size + 4
    }
  }
  const sectionGap = (px = 8) => { y += px }
  const rule = () => {
    doc.setDrawColor(180); doc.setLineWidth(0.5)
    doc.line(MARGIN, y, pageW - MARGIN, y); y += 10
  }

  // ── Header ──────────────────────────────────────────────────────────────
  doc.setFont('helvetica', 'bold'); doc.setFontSize(18)
  doc.text('Muscle Atlas — Triage Report', MARGIN, y); y += 22
  doc.setFont('helvetica', 'normal'); doc.setFontSize(9); doc.setTextColor(120)
  doc.text(
    `Generated ${opts.sessionDate.toLocaleString()}` +
    (opts.patientName ? `  •  Patient: ${opts.patientName}` : ''),
    MARGIN, y,
  )
  y += 14
  doc.setTextColor(0)
  rule()

  // ── Disclaimer ─────────────────────────────────────────────────────────
  writeLine('NOT A MEDICAL DIAGNOSIS', 10, true)
  writeLine(
    'This report is generated by an AI triage assistant grounded on a curated database of muscle pain referral patterns. It is intended as a discussion aid for licensed clinicians and is NOT a substitute for professional medical evaluation. Persistent or worsening symptoms warrant in-person assessment.',
    9,
  )
  sectionGap(); rule()

  // ── Reasoning ──────────────────────────────────────────────────────────
  writeLine('AI ASSESSMENT', 11, true); sectionGap(2)
  writeLine(opts.differential.reasoning || '(no narrative provided)', 10)
  sectionGap()

  // ── Red flags ──────────────────────────────────────────────────────────
  if (opts.differential.red_flags.length > 0) {
    doc.setTextColor(180, 30, 30)
    writeLine('RED FLAGS — SEEK PROFESSIONAL CARE', 11, true)
    doc.setTextColor(0)
    for (const f of opts.differential.red_flags) writeLine('• ' + f, 10)
    sectionGap(); rule()
  }

  // ── Differential table ────────────────────────────────────────────────
  writeLine('RANKED MUSCLE DIFFERENTIAL', 11, true); sectionGap(4)

  doc.setFont('helvetica', 'bold'); doc.setFontSize(9); doc.setTextColor(80)
  doc.text('#',           MARGIN,       y)
  doc.text('Muscle',      MARGIN + 22,  y)
  doc.text('Match Type',  MARGIN + 250, y)
  doc.text('Confidence',  MARGIN + 360, y)
  y += 14
  doc.setTextColor(0); doc.setLineWidth(0.3); doc.setDrawColor(200)
  doc.line(MARGIN, y - 10, pageW - MARGIN, y - 10)

  doc.setFont('helvetica', 'normal'); doc.setFontSize(10)
  opts.contributions.slice(0, 12).forEach((c, i) => {
    if (y > pageH - MARGIN) { doc.addPage(); y = MARGIN }
    const pct = (c.probability * 100).toFixed(0) + '%'
    doc.text(`${i + 1}.`,                  MARGIN,       y)
    doc.text(c.common_name,                MARGIN + 22,  y)
    doc.text(c.matchType,                  MARGIN + 250, y)
    doc.text(pct,                          MARGIN + 360, y)
    // confidence bar
    const barX = MARGIN + 400
    const barW = pageW - MARGIN - barX
    doc.setFillColor(245, 245, 245); doc.rect(barX, y - 8, barW, 8, 'F')
    doc.setFillColor(255, 140, 0);   doc.rect(barX, y - 8, barW * c.probability, 8, 'F')
    y += 16
  })
  sectionGap(); rule()

  // ── Modifiers ─────────────────────────────────────────────────────────
  if (opts.differential.worsens.length || opts.differential.relieves.length) {
    writeLine('PATIENT-REPORTED MODIFIERS', 11, true); sectionGap(2)
    if (opts.differential.worsens.length) {
      writeLine('Worsens:', 10, true)
      for (const w of opts.differential.worsens) writeLine('• ' + w, 10)
    }
    if (opts.differential.relieves.length) {
      writeLine('Relieves:', 10, true)
      for (const r of opts.differential.relieves) writeLine('• ' + r, 10)
    }
    sectionGap(); rule()
  }

  // ── Conversation transcript ──────────────────────────────────────────
  writeLine('CONVERSATION TRANSCRIPT', 11, true); sectionGap(2)
  for (const m of opts.history) {
    const ts = new Date(m.ts).toLocaleTimeString()
    writeLine(`${m.role === 'user' ? 'Patient' : 'AI'} — ${ts}`, 9, true)
    writeLine(m.content, 10)
    sectionGap(4)
  }

  // ── Save ──────────────────────────────────────────────────────────────
  const fname = `muscle-atlas-triage-${opts.sessionDate.toISOString().slice(0, 10)}.pdf`
  doc.save(fname)
}
